sudo: required

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=unstable TRAVIS_DEBIAN_SECURITY_UPDATES=false
  - TRAVIS_DEBIAN_DISTRIBUTION=testing

services:
  - docker

script:
  # build the debian package
  - wget -O- http://travis.debian.net/script.sh | sh -

after_script:
  # run lintian after build
  - sudo apt-get install -qq --no-install-recommends lintian
  - lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.deb && lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.dsc

#notifications:
#  email: false

branches:
  except:
    - /^debian\/\d/
