sudo: required
dist: trusty

matrix:
  include:
  - env: TRAVIS_DEBIAN_DISTRIBUTION=unstable
  - env: TRAVIS_DEBIAN_DISTRIBUTION=testing
  - env: TRAVIS_DEBIAN_DISTRIBUTION=stable
  allow_failures:
  - env: TRAVIS_DEBIAN_DISTRIBUTION=stable

services:
  - docker

script:
  # build the debian package
  - wget -O- http://travis.debian.net/script.sh | sh -

#notifications:
#  email: false

branches:
  except:
    - /^debian\/\d/
